server:
  port: 8091
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8651/eureka

spring:
  application:
    name: School
  config:
    import: optional:configserver:http://localhost:8888


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/students?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true